### PR TITLE
add all the docs

### PR DESCRIPTION
**Pull request by Nikolaj-K**
* Adding about a third of all scaladoc documentations. The doc scheme used throughout below. It has dots `.` at the end of all sentences and `...` in the `@param` line. I don't make much use of `@see` yet, but once I understand stuff better more notes are in place.

```scala
/** Improves a guess for a square root computation.
  * 
  * Provided a value interpreted as the square of a value x and a guess 
  * for x, improve the guess using the Babylonian method. To that end, 
  * compute the multiplicative complement of the guess and return the 
  * mean. Iterating this function on xg will give a value converging towards 
  * the real square root.
  * @param x2 ... Value we seek the square root x of.
  * @param xg ... Initial guess for x.
  * @return An improvement over xg.
  * @note The value xg should be positive and smaller than x2.
  * @example improvedSqrtGuess(4, 2.3) // evaluates to 2.0196...
  * @see [[https://en.wikipedia.org/wiki/Newton%27s_method wikipedia/Newtons_method]]
  * @todo Remove all unnecessary comments from the body of the function
  */
def improvedSqrtGuess(x2 : Double, xg : Double): Double = { 
  val xc = x2 / xg // The multiplicative complement of the guess.
  (xg + xc) / 2
}
```

* Also on all remaining `def`, `class`, `object` and `trait`, I annotate the spot with `\\ doc`.
* Some explanations are cursory and functions that are completely obvious just have a documentation of the form `/** what-it-does */`.
* Add `//end so-and-so` comment for brackets of (mostly) classes and object extending one IDE page.
* Added `// tmp comment` over much of the commented out (debug) code, i.e. code to be removed from dev eventually.
* scalafmt formated almost all files. That affects some larger {}-blocks and so there's a diff that's however just line breaks.
* Added end of line newlines, removed all multiple newlines and there are newlines between most vars.
* Prepared, in the import sections at the top of files, moving constellation module imports below generic module imports

One can generate a html page via `sbt doc` or just `doc` in the intelliJ sbt console. That one gets generated under 
`constellation/target/scala-x.xx/api/index.html`. 
Not that I think people use those html's all too often.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
I think merges of code block removals in dev won't get picked up properly if I keep this up, so if you want changes of the like, tell me what to keep or not and then I'll go through it again and make sure I'll not include stale code before a potential merge.

**Comment by Nikolaj-K** [comment]
@ryle-goehausen Indeed I used that scalafmt tool, but I shouldn't have used it in this PR on so many files as that just makes for too many files to read. I suppose the more conventient way for you to merge it in time will be if I'll make another branch tomorrow that's a bit more lean and decline this PR. 

>We're using the IntelliJ standard doc string everywhere right now for function / class docstrings. I'm not sure we should deviate from that.
Please tell me what you prefer and I'll run with that. That said, it's quite a stratch to say that there's any convention enforced in the code base right now. I've found different ones and the "..." is also there. 

You
 do a
>comment 
thee, so I'm not sure. Are you saying
a)
```
/**
 * Transaction builder (for local use)
```
or

b)
```
/**
  * Transaction builder (for local use)
```
or why not 
c)
```
/** Transaction builder (for local use)
  * 
```
It seems the last is the leanest but again, give your preferences.

Do you also explicitly want to avoid other @'s than param and return or was that just your example.

The `// end` isn't usually a convention but some code files here have 600 lines even without documentation, so that's why I inserted some - for structure.

If I can't salvage this PR, I'll put up a more conservative in the next days. I'd still put the `// doc` on top of functions in as a reminder of shame, unless I shouldn't.

**Comment by ryle-goehausen** [comment]
I'm not sure we need to enforce the differences between a/b/c

Scala lang uses the c) convention i.e.

>   /** Constructs a `BigInt` whose value is equal to that of the
   *  specified integer value.
   *
   *  @param i the specified integer value
   *  @return  the constructed `BigInt`
   */
  def apply(i: Int): BigInt =
    if (minCached <= i && i <= maxCached) {
      val offset = i - minCached
      var n = cache(offset)
      if (n eq null) { n = new BigInt(BigInteger.valueOf(i.toLong)); cache(offset) = n }
      n
    } else new BigInt(BigInteger.valueOf(i.toLong))

But IJ prompts you after autocompleting /** to the next line. I don't think it matters to enforce this but c) is preferable (or in general anything that is standard in Scala libs.) If we can auto format them that's fine too. Just don't want to impose an overhead on someone adding new stuff.

Same with other @ mentions. I think they're fine anywhere as an additional piece of information wherever that helps, but shouldn't necessarily be enforced. 

The // doc shame reminds are no big deal, we can fill them in eventually.

I'm also not really opposed to the other comments in general (for structure), more so just clarifying that they shouldn't be a style requirement (or enforced at a code level anywhere.)

If you wanna remake PR with changes we can accept it quickly before it gets out of sync. Sorry about the big changes.

**Comment by Nikolaj-K** [comment]
>If you wanna remake PR with changes we can accept it quickly before it gets out of sync. Sorry about the big changes.

No big deal to remake it as I went through it to read the code base and added stuff on the side.
To make the "non-conflictingness" of the other PR branch more appearent, I'll refrain from the auto-formating this time around.

---

Your first and second example differ from one another in that the first does
`@param i: the specified integer value`
or rather
`@param i : the specified integer value`
while in the latter you then just do
`@param i: the specified integer value`

If you don't want 
`@param i ... the specified integer value`
then I'd be fore
`@param i: the specified integer value`

but I get your point of not demanding a particular structure. That said, once 50% of code is in a certain style, then if peole document at all, they will likely adopt the style they see, so I don't expect formalization to get in the way.

**Comment by Nikolaj-K** [comment]
I've added the example and the discussed note on a very weekly enforced standard to the Constributions Guideline

https://github.com/Constellation-Labs/constellation/wiki/Contribution-guidelines

(Thankfully I can still edit the Wiki :P)

**Comment by Nikolaj-K** [comment]
Closing this in favour of https://github.com/Constellation-Labs/constellation/pull/265.

**Pull request closed without merging**
