### PR TITLE
New docs configuration and small app changes

### PR DESCRIPTION
**Pull request by tylerprete**
Our new docs are built with [MkDocs](https://www.mkdocs.org/) and served at https://constellation-labs.github.io/constellation/.

See our [gh-pages readme](readme-gh-pages.md) for instructions.

The app changes are to allow specifying a seed peer to join on startup more easily. This should be even easier (cmd-line args), but we'll do that in another PR.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
Looks neat!
Can the hyperlink also reach further than the docs folder, e.g. to the wiki or beyond? 
Right now you got some plaintext in html and some from the .md files. Would there be a preferred way to source from? Seems like Taking text from the docs md's instead of writing to html is smarter, but donno. 
And on view-deployment in the environment a day ago I saw he didn't render the emojis. Are they discouraged for that context or is it a matter of having a plugin?

**Comment by tylerprete** [comment]
Thanks! And sure, hyperlinks can reach anywhere. I plan on integrating some more of the docs folder too. Probably makes sense to move most of the docs folder over, but I wanted to start small.

Sorry, not sure what you mean by plaintext vs markdown. All the files in the new folder are markdown?

Not quite following the last bit. Where did you see un-rendered emoji?

**Comment by Nikolaj-K** [comment]
> I plan on integrating some more of the docs folder too. 

There's maybe an efficient way where you don't need to have e.g. the image files in both branches. 

>Sorry, not sure what you mean by plaintext vs markdown. All the files in the new folder are markdown?

You have e.g. the body of the Introduction page as plaintext in html ("Documentation for the Constellation Labs DAG project. Source available on Github."), while you import other text from the .md docs (e.g. the "Design choices" page). 
Maintaining two sources of plaintext might be cumbersome, so I meant it may be more efficient to write the whole thing in the .md docs.

I `pip installed`the mkdocs tool and deployed to 8000, but I'm missing the ylm. I saw you made a comment but on the fly I couldn't find the right spects to import the /constellation content. 

Btw. I suppse those ylm comments should be in the readme of that gh-pages branch, I had to look at the diff to read that readme instructions :D

Once it runs I'll also look at the emoji thing.

>Not quite following the last bit. Where did you see un-rendered emoji?

I can't find it now, which might be because the "View Deployment" buttons all link to the most recent deployed docs. But I'm under the impression that when skimming it yesterday, I saw one of the :some-emoji: things not being picked up in the deployed docs. If I'm not confused and that's the case, then one may either deprecate the emojis in the readme or make them work on the readme site.

**Comment by tylerprete** [comment]
Responding to the latter comment first. Github allows you to back the github.io page from either files in master/docs (and only master), or a gh-pages branch. I chose to go with the gh-pages route for now.

As for image duplication -- I'm not particularly concerned about it since there aren't very many. One fairly easy option if we cared would be to host the images elsewhere and just reference them. Switching to the master/docs option would make it easier as well. But not a major concern.

I understand what you mean by html / .md mixing now. The plan will be to port it all over to this new format. I moved that "Design choices" page over from the docs folder without tweaking it to a local reference, but that can be resolved fairly easily.

My main focus for this initial release was getting the "Running a Node" page up and running, but I do want to port the rest over.

As for running "mkdocs serve", are you running it from the root checkout directory, or the "docs-gh-pages" directory?

It should be the root directory on "launch-node" branch right now. Though I'm about to merge this into dev, so you'll be able to do it from there as well.

**Comment by Nikolaj-K** [comment]
I had called it from the root but not the launch-node I think. 
Okay, I'll run it again once you got in and merge in what you planned and see where to go from there. Thanks for the perspective 

---

semi-related: I just wrote a small script to read the repo and make a word cloud weighted by occurrence

<p align="center"></p>

https://i.imgur.com/YUJdsB9.png

**Pull request merged**
