### PR TITLE
Remove unsafe uses of IO.pure.

### PR DESCRIPTION
**Pull request by tylerprete**
IO.pure will memoize the value, so only use for things that truly return a constant value.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
>only use for
If it's going to stay, write the comment to the file?

**Comment by tylerprete** [comment]
@Nikolaj-K which file?

**Comment by Nikolaj-K** [comment]
I initially meant the Storage one, but it might go for everywhere where the comment applies. (I read it as a warning for further usage of those member functions and in that case it could be worth making the remark persistent.)

**Comment by ryle-goehausen** [comment]
> I initially meant the Storage one, but it might go for everywhere where the comment applies. (I read it as a warning for further usage of those member functions and in that case it could be worth making the remark persistent.)

This is documented in the definition of IO.pure

**Comment by tylerprete** [comment]
@Nikolaj-K This is already documented at the function IO.pure. It was just applied inappropriately. https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IO.scala#L988

**Comment by Nikolaj-K** [comment]
I see, thanks.

**Pull request merged**
