### PR TITLE
add all the docs v2

### PR DESCRIPTION
**Pull request by Nikolaj-K**
This is the discussed less intrustive setup for the previous PR at https://github.com/Constellation-Labs/constellation/pull/258: For now it's merely
- newlines, also grouping constellation file imports together
- the generic Documentation lines 
- moved constellation imports to the bottom of the imports lists

and I'll gradually add back the relevant docs. 
I wrote a script to insert the latter and therefore some classes and functions may now have two documentations stacked upon each other - I checked but if I oversaw some, I'll get rid of such double documentation lines in time and thus remove the noise.

This PR can (should) be merged directly as you find it, since when this is in, it makes adding further documentation easier (less conflicts).

---
As a side note, since this github group is smaller now, I've set up a low-access-barrier github group with downstream forks, so that people can work on their branches in public if they want to do so. You may point people to the Discord and approach me to get added there. 
It can also be used as dev group repo for externals who want to write stuff on top of the protocol (or related Scala tools). 
https://github.com/const-value
This PR also comes from that groups fork. 
It already has 5 members. And it has a clever name 😎 

---

Here's some statistics of the code base btw., that I got as a side product:
```json
def: 479
case class: 104
override def: 73
class: 69
object: 47
trait: 16
implicit class: 11
private def: 10
implicit def: 5
final case object: 4
case object: 4
sealed trait: 4
final case class: 1
```

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
E2ETest breaking, doubtful it it's the changes here:

```haskell
19:39:47.679 INFO  E2ETest {org.constellation.cluster.E2ETest $anonfun$new$1} - DownloadNode API Port: 9050
19:39:47.687 INFO  Simulation {org.constellation.util.Simulation awaitConditionMet} - Node state not ready Waiting 3 sec. Num attempts: 1 out of 20
19:40:10.781 INFO  Simulation {org.constellation.cluster.E2ETest $anonfun$new$1} - Stopping transactions to run parity check
[info] - should demonstrate full flow *** FAILED ***
[info]   List("873", "869") had size 2 instead of expected size 1 (E2ETest.scala:189)
```

**Comment by tylerprete** [comment]
@Nikolaj-K We talked and we're not going to accept this PR as is.

As a team we don't find the doc shaming particularly valuable. If you'd like to submit this with just the reworked imports, I'd accept it. If you'd like to work on actually commenting a file or two, I'd be happy to review that -- but we don't want to clutter the codebase with ```/** Documentation. */```

**Comment by Nikolaj-K** [comment]
Got it, I'll remove it when I get home.

I suppose they'd soon enough would be removed anyway, once they indeed become actual documentations or removed if not necessary at all. So they'd just be a tag to help find which parts were not looked at.

**Comment by Nikolaj-K** [comment]
Remove the doc placeholders now. 

E2ETest again complaining:
```haskell
17:23:29.702 INFO  E2ETest {org.constellation.cluster.E2ETest $anonfun$new$1} - DownloadNode API Port: 9050
17:23:29.712 INFO  Simulation {org.constellation.util.Simulation awaitConditionMet} - Node state not ready Waiting 3 sec. Num attempts: 1 out of 20
17:23:52.810 INFO  Simulation {org.constellation.cluster.E2ETest $anonfun$new$1} - Stopping transactions to run parity check
Num invalid 5
[{"id":0,"parentIds":[7,141],"color":"blue"}, ...
```

**Comment by tylerprete** [comment]
@Nikolaj-K I get where you're coming from -- we'll try and add some more docs as applicable, but tbh as we're a small team it's not our top priority right now. That said, this updated branch looks pretty good. It's only failing because we have a flaky test -- I can rerun it til it passes and we'll get it merged.

**Comment by Nikolaj-K** [comment]
@tylerprete Ha, yeah I just saw you retriggering branches and so I pushed it again to trigger the test that way for a test.
I know it's not your top priority, that's where lurking devs come in. You have my sword ⚔️

**Pull request merged**
